dataUsers ={
   "id":"0",
   "food_drinks":
      {
         "Чай":{"price":"50","count":0},
         "Кола":{"price":"150","count":0},
         "Морс":{"price":"50","count":0},
         "Салат":{"price":"250","count":0},
         "Суп":{"price":"250","count":0},
         "Сэндвич":{"price":"150","count":0},
   },
   "services":{
      "Подушка":{"count":0},
      "Одеяло":{"count":0},
      "Приборы":{"count":0},
      "Наушники":{"count":0},
      "Телефон":{"count":0},
      "Проводник":{"call":False},
   },
   "report":[]
}